### PR TITLE
remove superfluous feature.xml files

### PR DESCRIPTION
**Pull request by acoburn**
the `features.xml` files are generated with the features-maven-plugin, so these files are no longer necessary.

### CODE REVIEW

**Comment by birkland** [comment]
Hi Aaron,

This doesn't build for me (I rm -rf `.m2/repository/org/fcrepo/apix` before building)

The way it was before:
* Each module `fcrepo-api-x-foo` had their own `fcrepo-api-x-foo/src/main/feature/feature.xml` file, which contained all feature-level dependencies (i.e. to pull in `camel-http4`, `camel-jetty` features, or whatever)
* Upon building the module, the features-maven plugin would create a `fcrepo-api-x-foo/target/features/feature.xml` file which merged the explicitly declared dependencies in `fcrepo-api-x-foo/src/main/feature/feature.xml` with the bundles in the module's dependency tree
* `fcrepo-api-x-karaf` has a `fcrepo-api-x-karaf/src/main/feature/feature.xml` which just enumerates the `fcrepo-api-x-*` features as dependencies.  
* Upon build, the features-maven-plugin expands each `fcrepo-api-x-*` dependency in the `fcrepo-api-x-karaf/src/main/feature/feature.xml` with the contents of that module's `fcrepo-api-x-foo/target/feature/feature.xml` file, and places the result in `fcrepo-api-x-karaf/target/src/main/feature/feature.xml`

So to illustrate, a module `fcrepo-api-x-foo` may have a features file `src/main/feature/feature.xml`
```
    <features>
        <feature name="fcrepo-api-x-foo">
            <feature>camel-special</feature>
         </feature>
    </features>
```

After building the module, the features-maven plugin creates `target/feature/feature.xml`
```
    <features>
        <feature name="fcrepo-api-x-foo">
            <feature>camel-special</feature>
            <bundle>bar</bundle>
            <bundle>baz</bundle>
         </feature>
    </features>
```

Now, fcrepo-api-x-karaf has its own `src/main/feature/feature.xml` file:
```
    <features>
        <feature name="fcrepo-api-x">
            <feature>fcrepo-api-x-foo</feature>
            <feature>fcrepo-api-x-whatever</feature>
        </feature>
    </features>
```

Acted upon by the features-maven-plugin, this finally results in:
```
    <features>
        <feature name="fcrepo-api-x">
            <feature>fcrepo-api-x-foo</feature>
            <feature>fcrepo-api-x-whatever</feature>
        </feature>
        <feature name="fcrepo-api-x-foo">
            <feature>camel-special</feature>
            <bundle>bar</bundle>
            <bundle>baz</bundle>
        </feature>
        <feature name="fcrepo-api-x-whatever">
            ...
        </feature>
    </features>
```

What's happening in this PR is that without the individual module `feature.xml` files to declare `<feature>camel-special</feature>`, individual modules are not having their camel dependencies satisfied when deployed in karaf.  So the feature files either need to be put back, or incorporated into `fcrepo-api-x-karaf/src/main/feature/feature.xml`, or documented that the user needs to supply them (and the ITs adjusted to do that)

Does that make sense?  The best solution would be the easiest to understand and least burdensome.  I'm not sure I know what that is!

**Comment by acoburn** [comment]
@birkland thanks for the explanation. I was confused about why this didn't build for me either (it did initially since I neglected to do the initial `rm -rf ~/.m2/repository/....`). What is odd, though, is that the XML syntax of these files is clearly incorrect (check out line 8 on each file). What would you think of having me revise this PR and just remove that line from the two `feature.xml` files?

**Comment by birkland** [comment]
@acoburn Sure..  I have no idea why everything worked fine in the first place (and didn't even throw a warning, as far as I can tell) with clearly malformed xml!

**Comment by acoburn** [comment]
@birkland I noticed the malformed XML and just assumed that "if the XML is malformed, then any XML parser should be throwing an error, and therefore those files must not be in use", which was clearly wrong. 

I've updated the PR to make the XML syntactically correct.

**Pull request merged**
