### PR TITLE
Make sure AutoCloseable resources are closed

### PR DESCRIPTION
**Pull request by birkland**
This is the result of auditing the codebase for resource leaks.  Includes
many fixes to unit tests that are likely unnecessary, but included for the sake
of cleanliness

Possibly related to #126

### CODE REVIEW

**Review by ajs6f — APPROVED** [review]
All these changes seem to me to be straightforward improvements.

**Comment by dannylamb** [comment]
@birkland I'll try and test this in isolation before https://github.com/Islandora-CLAW/Alpaca/pull/42 to see if I can pin down precisely what's causing our issue.

**Comment by birkland** [comment]
@dannylamb Great. [Jenkins](http://jenkins.fcrepo.org/) should finish and publish its snapshot build of API-X in a few minutes

**Comment by dannylamb** [comment]
So this hasn't resolved the issue, but it has turned it from intermittent to easily reproducable.  :+1: to that.

**Comment by birkland** [comment]
That seems strange, but I'll take it.  Also taking another look at the initial CLAW issue..

**Comment by ajs6f** [comment]
Easily repro is certainly good. And certainly weird.

**Pull request merged**
